### ISSUE TITLE
[BUG] Double movement

### ISSUE THREAD

**Issue by non-descriptive** [ckaznable/poketex#10]
Looks like it has issues with button handlingsince it handles both up and down states the same time. So when I try to navigate throw list with up/down buttons it does two steps per button. 

Tested on windos, but I guess it's non platform related issue

**Comment by ckaznable** [comment]
Are you using the arrow keys or `hjkl` to navigate?

Because it works fine on my Ubuntu 22.04

**Comment by ckaznable** [comment]
https://github.com/crossterm-rs/crossterm/issues/752

It seems to be a problem only for windows. I will find time to test this on windows.

**Comment by non-descriptive** [comment]
Checked on Debian as well, works fine. So I guess it's really crossterm's windows specific bug.

**Comment by ckaznable** [comment]
v1.3.0 published
