### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by rashil2000** [ckaznable/poketex#21]
I think it would be pretty cool if Poketex could show a pixelated, bitmap like sprite of the Pokemon, besides the stats table, on the left side of it. Browsing through Serebii, I found that it's pretty easy to fetch the image. Since most terminals don't support full-res image rendering, a low-res icon could be used instead. The links can be constructed in this way:
- Low-res - `https://www.serebii.net/pokedex-sv/icon/<id>.png`
- High-res - `https://www.serebii.net/pokemon/art/<id>.png`

where `<id>` is the global Pokedex number of that Pokemon.

**Comment by ckaznable** [comment]
Thanks for the issue. I'll take a look at it sometime.

**Comment by ckaznable** [comment]
I've issued a release to support images, currently using the ansi image source, but it's only supported up to 8th gen at the moment, pending an upstream update.

**Comment by rashil2000** [comment]
It looks great! Thanks for implementing this. 

Should I close the issue?

**Comment by ckaznable** [comment]
If you think it's okay, you can close it. Thank you.
